FROM continuumio/miniconda3

WORKDIR /app

# Create the environment:
COPY aida_entity.yaml .
RUN conda env create -f aida_entity.yaml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "aida_entity", "/bin/bash", "-c"]

# Make sure the environment is activated:
RUN echo "Make sure allennlp is installed:"
RUN python -c "import allennlp"

# The code to run when container is started:
COPY ./entity_api ./entity_api
ENTRYPOINT ["conda", "run", "-n", "aida_entity", "python", "./entity_api/app.py"]
