FROM ubuntu:latest

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt update && \
    apt upgrade -y && \
    apt install wget -y &&\
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
RUN /opt/conda/bin/conda create -n py36 python=3.6
RUN echo "conda activate py36" >> ~/.bashrc

RUN /opt/conda/bin/conda install pytorch=1.3 anaconda -y
RUN /opt/conda/bin/pip install requests flask
RUN /opt/conda/bin/pip install flashtext
RUN /opt/conda/bin/conda install allennlp -c pytorch -c allennlp -c conda-forge && \
    /opt/conda/bin/conda clean -tipsy

ADD ./entity_api ./entity_api

CMD /bin/bash